# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_profile', '0002_customer_full_name'),
        ('entity_management', '0005_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_profile.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity_management.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.DecimalField(decimal_places=2, max_digits=3)),
                ('associated_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associated_product', to='entity_management.Product')),
                ('root_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='root_product', to='entity_management.Product')),
            ],
        ),
    ]
