# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderlineitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_management.Product'),
        ),
        migrations.AlterField(
            model_name='productassociation',
            name='associated_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_product', to='entity_management.Product'),
        ),
        migrations.AlterField(
            model_name='productassociation',
            name='root_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_product', to='entity_management.Product'),
        ),
    ]
