# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_auto_20170719_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productassociation',
            name='probability',
            field=models.FloatField(),
        ),
    ]
