# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_auto_20170724_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_date_of_payment',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='desosit_slip_photo',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
