# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_auto_20170724_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
