# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_auto_20170724_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='photo',
            new_name='customer_deposit_photo',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
