# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_auto_20170719_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitems',
            name='parent_order',
        ),
        migrations.RemoveField(
            model_name='orderlineitems',
            name='product',
        ),
        migrations.DeleteModel(
            name='OrderLineItems',
        ),
    ]
