# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_order_payment_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='queue_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
