# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_auto_20170724_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='desosit_slip_photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
