# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_order_queue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_held',
            field=models.BooleanField(default=True),
        ),
    ]
