# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_order_stock_held'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stock_held',
        ),
    ]
