# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_auto_20170724_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='desosit_slip_photo',
            new_name='deposit_slip_photo',
        ),
    ]
