# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_auto_20170724_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deposit_slip_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
