# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_auto_20170724_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deposit_slip_photo',
        ),
        migrations.AddField(
            model_name='order',
            name='photo',
            field=models.FileField(blank=True, default='/static/images/product.png', null=True, upload_to=''),
        ),
    ]
