# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_auto_20170724_1544'),
        ('order_management', '0008_auto_20170724_1540'),
    ]

    operations = [
    ]
