# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_merge_20170724_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_date_of_payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_deposit_photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_payment_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
