# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='Sample', max_length=256),
            preserve_default=False,
        ),
    ]
