# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity_management', '0005_product_is_active'),
        ('customer_profile', '0002_customer_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_management.Product')),
            ],
        ),
    ]
