# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0005_userwish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWish',
            new_name='Wishlist',
        ),
    ]
