# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0006_auto_20170722_1834'),
        ('customer_profile', '0006_auto_20170722_1831'),
    ]

    operations = [
    ]
