# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity_management.Stall'),
        ),
    ]
