# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='/static/images/product.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
