# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity_management', '0002_auto_20170723_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_management.Stall'),
        ),
    ]
