# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_management', '0003_auto_20170626_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, default='/static/images/product.png', null=True, upload_to=''),
        ),
    ]
