# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_management', '0003_auto_20170724_0157'),
        ('entity_management', '0003_auto_20170724_1542'),
    ]

    operations = [
    ]
