# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_management', '0004_auto_20170704_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
